capybara/urls.py
from django.contrib import admin
from django.urls import path, include
#add include funtion to the import 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')), #'' represents the root route
]
#by convention, we always add a comma at the end of each path

#this section is the equivalent of server.js using mongoose. 

main_app/urls.py
#this is the quivalent of routers folder in mongoose


from django.urls import path 
from . import views 

#path function that will be used to define each route

urlpatterns = [
    path('', views.home, name='home'), #root path to views
    path('about/', views.about, name='about'),
    #route for capybaras index
    path('capybaras/', views.capybaras_index, name='index'),
    path('capybaras/<int:capybara_id>/', views.capybaras_detail, name='detail'),
    path('capybaras/create', views.CapybaraCreate.as_view(), name='capybaras_create'),
    path('capybaras/<int:pk>/update/', views.CapybaraUpdate.as_view(), name='capybaras_update'),
    path('capybaras/<int:pk>/delete/', views.CapybaraDelete.as_view(), name='capybaras_delete'),
    path('capybaras/<int:capybara_id>/add_feeding/', views.add_feeding, name='add_feeding'),
    path('capybaras/<int:capybara_id>/assoc_toy/<int:toy_id>/', views.assoc_toy, name='assoc_toy'),
]

#<int:capybara_id>reffers to the id of the papybara we are working with

main_app/models.py
from django.db import models
# Import the reverse function
from django.urls import reverse




MEALS = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner'),
)

# Create your models here.
class Toy(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('toys_detail', kwargs={'pk': self.id})



class Capybara(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    personality = models.TextField(max_length=250)
    age = models.IntegerField()
  # Add the M:M relationship
    toys = models.ManyToManyField(Toy)

    def get_absolute_url(self):
        return reverse('detail', kwargs={'capybara_id': self.id})
    
    def __str__(self):
        return f"{self.name} is {self.age} years old"


# Add new Feeding model below Capymodel
class Feeding(models.Model):
  date = models.DateField('feeding date')
  meal = models.CharField(
    max_length=1,
     #add the 'choices' field options
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0]
  )
      
# Create a capybara_id FK
  capybara = models.ForeignKey(Capybara, on_delete=models.CASCADE)

  class Meta: 
    ordering = ['-date']

  def __str__(self):
    #Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_meal_display()} on {self.date}"

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding 

class FeedingForm(ModelForm):
	class Meta:
		model = Feeding 
		fields = ['date', 'meal']

main_app/views.py
##VIEW FUNCTIONS
# #this is the equivalent of mongoose controller functions

from django.shortcuts import render, redirect

from django.views.generic.edit import CreateView, UpdateView, DeleteView
#Define the following import
from .models import Capybara, Toy
#Import the FeedingForm 
from .forms import FeedingForm



#Define the home view
def home(request):
    return render(request, 'home.html')
#this is just returning a string. We need to work on a database

def about(request):
    return render(request, 'about.html') #rendering to file inside templates

def capybaras_index(request):
    capybaras = Capybara.objects.all()
    return render(request, 'capybaras/index.html', { 'capybaras': capybaras })


def capybaras_detail(request, capybara_id):
    capybara = Capybara.objects.get(id=capybara_id)
    #instantiate FeedingForm to be rendered in the template
    toys_capybara_doesnt_have = Toy.objects.exclude(id__in = capybara.toys.all().values_list('id'))
    feeding_form = FeedingForm()
    return render(request, 'capybaras/detail.html', { 
        #include the capybara and feeding_form in the context 
        'capybara': capybara, 'feeding_form': feeding_form,
        'toys': toys_capybara_doesnt_have
    })

class CapybaraCreate(CreateView):
    model = Capybara
    fields = ['name', 'location', 'personality', 'age'] #this could also have been written as fields = ['name', 'location', 'personality', 'age']
    success_url = '/capybaras/'

class CapybaraUpdate(UpdateView):
    model = Capybara
    fields = ['location', 'personality', 'age']
    success_url = '/capybaras/'

class CapybaraDelete(DeleteView):
    model = Capybara
    success_url = '/capybaras/'

def add_feeding(request, capybara_id):
 # create a ModelForm instance using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the capybara_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.capybara_id = capybara_id
    new_feeding.save()
  return redirect('detail', capybara_id=capybara_id)

def assoc_toy(request, capybara_id, toy_id):
  # Note that you can pass a toy's id instead of the whole object
  Capybara.objects.get(id=capybara_id).toys.add(toy_id)
  return redirect('detail', capybara_id=capybara_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <h1>ABOUT CAPYBARAS</h1>
<hr />
<p>The Viral Capybaras!</p>
<iframe width="560" height="315" src="https://www.youtube.com/embed/EgIl0zo506A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Capybara Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Home</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'capybaras_create' %}">Add a Capybara</a></li>
          <li><a href="{% url 'index' %}">View Capybaras</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Capybaras &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/capybaras/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Capybara Details</h1>


<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
      <span class="card-title">{{ capybara.name }}</span>
      <p>Location: {{ capybara.location }}</p>
      <p>Description: {{ capybara.description }}</p>
      {% if capybara.age > 0 %}
        <p>Age: {{ capybara.age }}</p>
      {% else %}
        <p>Age: Pup</p>
      {% endif %}
    </div>
    <div class="card-action">
      <a href="{% url 'capybaras_update' capybara.id %}">Edit</a>
      <a href="{% url 'capybaras_delete' capybara.id %}">Delete</a>
    </div>
  </div>
</div>
<div class="col s6">
  <form action="{% url 'add_feeding' capybara.id %}" method="post">
    {% csrf_token %}
    {{ feeding_form.as_p }}
    <input type="submit" class="btn" value="Add Feeding">
  </form>
  <table class="striped">
    <thead>
      <tr><th>Date</th><th>Meal</th></tr>
    </thead>
    <tbody>
      {% for feeding in capybara.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>

<!-- This is all new markup to be added just above the <script> tag -->
  <hr>
  <div class="row">
    <div class="col s6">
      <h3>{{ capybara.name }}'s Toys</h3>
      {% if capybara.toys.count %}
        {% for toy in capybara.toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
              </span>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Toys :(</h5>
      {% endif %}
    </div>
    <!-- Available toys will come after this line -->
    <div class="col s6">
      <h3>Available Toys</h3>
      {% if toys.count %}
        {% for toy in toys.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_toy' capybara.id toy.id %}" method="post">
                  {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
            
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{capybara.name}} Already Has All Toys Available</h5>
      {% endif %}
    </div>
  </div>
  

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // add additional JS to initialize select below
  const selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/capybaras/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Capybara List</h1>

{% for capybara in capybaras %}
  <div class="card">
   <a href="{% url 'detail' capybara.id %}">
    <div class="card-content">
      <span class="card-title">{{ capybara.name }}</span>
      <p>Location: {{ capybara.location }}</p>
      <p>Description: {{ capybara.personality }}</p>
      {% if capybara.age > 0 %}
        <p>Age: {{ capybara.age }}</p>
      {% else %}
        <p>Age: Capybara Pup</p>
      {% endif %}
    </div>
  </div>
{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h4 class="home-main">Capybaras are taking the internet by storm!</h4>
    <img src="https://i.imgur.com/jPPiIBX.gif" alt="">
    <h5>These beautiful creatures are loved by many,
         and we are here to share footage of them living in their natural habitat!</h5>
    {% endblock %}
    

main_app/templates/main_app/capybara_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Capy</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' capybara.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/capybara_form.html
{% extends 'base.html' %}

{% block content %}
<!-- The following if statement will only show when editing, not creating a capybara -->


{% if object %}
	<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
	<h1>Add A Capy!</h1>
{% endif %}
	

  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}